using Briscola.Api.Dtos;

namespace Briscola.Api.Hubs;

/// <summary>
/// Server-to-client method surface of <see cref="GameHub"/>. Implementations
/// are auto-generated by SignalR; <see cref="GameEventDispatcher"/> (Phase
/// 5.2b) is the only code that calls these methods on broadcast events.
/// The hub itself only calls <see cref="ChatMessage"/> directly when
/// echoing chat to <c>game:{gameId}</c> groups.
/// </summary>
public interface IGameClient
{
    Task Joined(RedactedStateForUserDto snapshot);

    Task StateUpdated(RedactedStateForUserDto snapshot);

    Task CardPlayed(CardPlayedDto evt);

    Task TrickResolved(TrickResolvedDto evt);

    Task CardsDrawn(CardsDrawnDto evt);

    Task PhaseChanged(string newPhase);

    Task GameFinished(GameFinishedDto evt);

    Task PlayerDisconnected(int seatIndex, DateTimeOffset graceDeadlineUtc);

    Task PlayerReconnected(int seatIndex);

    Task IdleWarning(int seatIndex, DateTimeOffset forfeitDeadlineUtc);

    Task ChatMessage(GameChatMessageDto message);

    Task InvalidMove(string code);
}
